### ISSUE TITLE
Color tags should match system style (Yosemite)

### ISSUE THREAD

**Issue by lludo** [antons/Gitbox-Tweaks#2]
The square icons look too small and blurry:

![screen shot 2015-01-27 at 12 01 43 pm](https://cloud.githubusercontent.com/assets/631630/5926018/ae1aede6-a61c-11e4-9f64-a97b3ee0cf37.png)

The system circular ones look better:

![screen shot 2015-01-27 at 12 01 19 pm](https://cloud.githubusercontent.com/assets/631630/5926019/ae1daa4a-a61c-11e4-96a3-fed890acd5c7.png)

**Comment by mdznr** [comment]
👍

**Comment by sudeepdua** [comment]
:+1:

**Comment by antons** [comment]
You’re welcome to contribute resources for the tags. I don’t use tags in Gitbox, so they’re low on my priority list.

**Comment by antons** [comment]
Thanks to @mdznr, tags look great in 1.2.
